### ISSUE TITLE
*BSD support

### ISSUE THREAD

**Issue by dch** [hwchen/keyring-rs#36] opened 2020-02-20 11:28 UTC
What is required to support keyring on a given unix system? FreeBSD presumably has something like gnome keyring in ports that could be used for this, or is it possible to point to a system like hashicorp vault as a generic secrets store?

**Comment by hwchen** [comment] 2020-02-25 14:23
Sorry for the delay in replying! I would love to support BSD, but am not sure what it would take. I’m happy to look into it when I have time, and am open to suggestions and pull requests.

**Comment by dch** [comment] 2020-02-25 14:37
thanks Walther,

Can you point out what library you require on linux at least? I can then see what's available
in FreeBSD for comparison.

**Comment by hwchen** [comment] 2020-02-25 14:42
I use secret-service, which is a protocol over dbus to interface with gnome keyring, kwallet, and other keyrings that implement the api.

https://github.com/hwchen/secret-service-rs
https://specifications.freedesktop.org/secret-service/latest/

**Comment by adobeDan** [comment] 2021-11-13 17:46
Hi @dch, we have updated to the latest secret-service, and I believe it runs on BSD.  Can you try out the latest 0.10.4 release on BSD and let us know what you find?  Be sure to install lib-dbus on your BSD system if it's not already installed with the OS.

**Comment by brotskydotcom** [comment] 2021-12-04 05:34
Hi @dch, I have been able to confirm that our recent 1.0 release runs on Free BSD if you use the Gnome desktop.  Closing this issue.

**Comment by messense** [comment] 2022-12-05 10:08
I believe *BSD support has regressed, on FreeBSD

```
$ cargo build
   Compiling keyring v2.0.0-alpha.3 (/root/code/keyring-rs)
error[E0433]: failed to resolve: use of undeclared crate or module `default`
   --> src/lib.rs:158:19
    |
158 |     let default = default::default_credential_builder();
    |                   ^^^^^^^ use of undeclared crate or module `default`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `keyring` due to previous error
```

Slightly change the code to use secret-service on FreeBSD

```diff
diff --git a/Cargo.toml b/Cargo.toml
index dfdab29..d72755d 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -28,6 +28,9 @@ security-framework = "2.6"
 secret-service = "2.0"
 linux-keyutils = { version = "0.2", features = ["std"] }

+[target.'cfg(target_os = "freebsd")'.dependencies]
+secret-service = "2.0"
+
 [target.'cfg(target_os = "windows")'.dependencies]
 byteorder = "1.2"
 winapi = { version =  "0.3", features = ["wincred", "winerror", "errhandlingapi", "minwindef"] }
diff --git a/src/lib.rs b/src/lib.rs
index 03f2030..5805ebe 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -118,6 +118,9 @@ use windows as default;
 #[cfg(all(target_os = "linux", feature = "linux-secret-service"))]
 use crate::secret_service as default;

+#[cfg(target_os = "freebsd"]
+use crate::secret_service as default;
+
 pub mod credential;
 pub mod error;
 pub mod mock;
@@ -129,7 +132,7 @@ pub mod ios;
 pub mod keyutils;
 #[cfg(target_os = "macos")]
 pub mod macos;
-#[cfg(target_os = "linux")]
+#[cfg(any(target_os = "linux", target_os = "freebsd"))]
 pub mod secret_service;
 #[cfg(target_os = "windows")]
 pub mod windows;
```

```bash
$ cargo build
   Compiling zbus v1.9.3
error[E0432]: unresolved import `nix::sys::socket::sockopt::PeerCredentials`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-1.9.3/src/connection.rs:163:44
    |
163 |         use nix::sys::socket::{getsockopt, sockopt::PeerCredentials};
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^ no `PeerCredentials` in `sys::socket::sockopt`

error[E0432]: unresolved import `nix::sys::socket::sockopt::PeerCredentials`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-1.9.3/src/azync/connection.rs:180:44
    |
180 |         use nix::sys::socket::{getsockopt, sockopt::PeerCredentials};
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^ no `PeerCredentials` in `sys::socket::sockopt`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `zbus` due to 2 previous errors
```

**Comment by messense** [comment] 2022-12-05 10:10
keyring 1.2.0 also don't compile on FreeBSD

```
error[E0583]: file not found for module `platform`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/lib.rs:79:1
   |
79 | mod platform;
   | ^^^^^^^^^^^^^
   |
   = help: to create the module `platform`, create file "/.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/platform.rs" or "/.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/platform/mod.rs"
error[E0412]: cannot find type `Error` in module `crate::platform`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/error.rs:15:38
   |
15 |     PlatformFailure(crate::platform::Error),
   |                                      ^^^^^ not found in `crate::platform`
   |
help: consider importing one of these items
   |
7  | use core::error::Error;
   |
7  | use core::fmt::Error;
   |
7  | use crate::Error;
   |
7  | use std::error::Error;
   |
     and 2 other candidates
help: if you import `Error`, refer to it directly
   |
15 -     PlatformFailure(crate::platform::Error),
15 +     PlatformFailure(Error),
   |
error[E0412]: cannot find type `Error` in module `crate::platform`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/error.rs:21:38
   |
21 |     NoStorageAccess(crate::platform::Error),
   |                                      ^^^^^ not found in `crate::platform`
   |
help: consider importing one of these items
   |
7  | use core::error::Error;
   |
7  | use core::fmt::Error;
   |
7  | use crate::Error;
   |
7  | use std::error::Error;
   |
     and 2 other candidates
help: if you import `Error`, refer to it directly
   |
21 -     NoStorageAccess(crate::platform::Error),
21 +     NoStorageAccess(Error),
   |
error[E0425]: cannot find function `platform` in module `platform`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/lib.rs:71:15
   |
71 |     platform::platform()
   |               ^^^^^^^^ not found in `platform`
error[E0425]: cannot find function `set_password` in module `platform`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/lib.rs:140:19
    |
140 |         platform::set_password(&self.target, password)
    |                   ^^^^^^^^^^^^ not found in `platform`
error[E0425]: cannot find function `get_password` in module `platform`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/lib.rs:148:19
    |
148 |         platform::get_password(&mut map)
    |                   ^^^^^^^^^^^^ not found in `platform`
error[E0425]: cannot find function `get_password` in module `platform`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/lib.rs:158:34
    |
158 |         let password = platform::get_password(&mut map)?;
    |                                  ^^^^^^^^^^^^ not found in `platform`
error[E0425]: cannot find function `delete_password` in module `platform`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/keyring-1.2.0/src/lib.rs:166:19
    |
166 |         platform::delete_password(&self.target)
    |                   ^^^^^^^^^^^^^^^ not found in `platform`
Some errors have detailed explanations: E0412, E0425, E0583.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `keyring` due to 8 previous errors
```

**Comment by brotskydotcom** [comment] 2022-12-27 06:39
Hi @messense, with the 1.0 release, platform support for keyring-rs became explicit, and FreeBSD has not been included in the supported platforms (because none of the maintainers use it, and GitHub Actions CI doesn't support it).  If you would like to submit a pull request that makes things run on freebsd, I am willing to consider including freebsd support as experimental. 

If you do want to work on this, I recommend you target the current head (2.0.0-alpha) rather than the 1.2 release, as platform support has changed quite a bit with the introduction of traits.  It should actually be a lot easier to include FreeBSD support in the new model than it would have been in the old one.

**Comment by ryanavella** [comment] 2023-01-30 18:13
secret-service 3.0 was [just published](https://crates.io/crates/secret-service/3.0.0), and I suspect it will fix several of the errors originating from zbus on FreeBSD.

If/when you decide to bump secret-service from 2.0 up to 3.0, I'd be willing to test this on FreeBSD.

**Comment by brotskydotcom** [comment] 2023-01-30 19:04
Hi @ryanavella, thanks for looking at this.  In fact, I have already done the port of keyring to use secret-service v3, but I couldn't release it to crates.io because the service hadn't been released.  (It uses the block interface that secret-service v3 has provided for sync clients such as keyrong).  If you would like to do some testing right away feel free to download and build [this published pre-release of keyring](https://github.com/hwchen/keyring-rs/releases/tag/v2.0.0-alpha.4). I anticipate that I will release a keyring 2.0 later this week to crates.io that uses the secret-service v3.

**Comment by ryanavella** [comment] 2023-01-30 20:29
Ah great, I was looking through the commit tags yesterday but somehow completely missed v2.0.0-alpha.4. I can confirm that after installing the `gnome-keyring` package and making a few small tweaks to Cargo.toml and lib.rs (similar to @messense's suggestion) it can compile on FreeBSD now.

The tests in error.rs and mock.rs all pass, but the tests in secret_service.rs all fail with `NoStorageAccess(NoResult)`. I suspect this could be due to some of my system's hardening settings, I'll play around some more and report my findings.

**Comment by brotskydotcom** [comment] 2023-01-31 05:46
Hi @ryanavella, I've just released v2.0.0-rc.1 (based on secret-service v3) to crates.io.  Please try the mods and see if this works on FreeBSD.

**Comment by ryanavella** [comment] 2023-02-15 20:16
Hi @brotskydotcom, I tried both v2.0.0-rc.1 and v2.0.0-rc.3, and with the same few small tweaks I can get it to compile on FreeBSD.

I also realized that I should be testing through the linux_test.sh script rather than through `cargo test`, and now I'm getting new errors. See the collapsed test results below.

You'll notice that all of the failed tests are looking for an object at the path `/org/freedesktop/secrets/collection/login`. FreeBSD typically doesn't have an `/org` top-level directory, and as far as I can tell this path doesn't correspond to any XDG directories, environment variables, or config settings, so I am not sure where it is coming from other than dbus or gnome-keyring itself.

I realize this is likely user-error on my part, so I'll keep experimenting to see if I can get a working gnome-keyring setup. In the meantime, if you want me to submit a PR for FreeBSD support I'd be willing to do that, only a few small changes are needed in lib.rs and Cargo.toml

### Test results

**Comment by ryanavella** [comment] 2023-02-15 20:37
Here is what the patch would look like, @messense would you be willing to try on your end as well? If you have configured gnome-keyring on your system, I'd be curious to know what the output of `./linux_test.sh` looks like for you.

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 9531b02..c5cc777 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -34,6 +34,9 @@ security-framework = "2.6"
 secret-service = { version = "3", optional = true }
 linux-keyutils = { version = "0.2", features = ["std"] }
 
+[target.'cfg(target_os = "freebsd")'.dependencies]
+secret-service = { version = "3", optional = true }
+
 [target.'cfg(target_os = "windows")'.dependencies]
 byteorder = "1.2"
 winapi = { version =  "0.3", features = ["wincred", "winerror", "errhandlingapi", "minwindef"] }
diff --git a/src/lib.rs b/src/lib.rs
index 2952e92..87282dc 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -122,6 +122,11 @@ use crate::secret_service as default;
 #[cfg(all(target_os = "linux", feature = "linux-default-keyutils"))]
 use keyutils as default;
 
+#[cfg(target_os = "freebsd")]
+pub mod secret_service;
+#[cfg(target_os = "freebsd")]
+use crate::secret_service as default;
+
 #[cfg(target_os = "windows")]
 pub mod windows;
 #[cfg(target_os = "windows")]
```

**Comment by brotskydotcom** [comment] 2023-02-15 20:45
Hi @ryanavella and hooray!  Thanks so much for trying with RC3, because maybe we can even get this into the v2 final release!  Please *do* submit a PR!

To help clarify what's happening in your tests: the "object path" used by secret-service has *nothing* to do with directory paths.  Your errors suggest that the linux-test.sh script, which is trying to create and unlock a default collection for secret service to use (canonically called "login"), is not actually getting that collection created on FreeBSD.  This makes sense because FreeBSD security is *way* better than linux security, so it probably won't allow access to the default collection headlessly at all.

As you will see from the docs, secret-service is not really suitable for use on headless boxes.  That test script really only exists so I can at least get some level of testing done on the secret-service code in an automated fashion on GitHub's Ubuntu build machines.  I will probably never add that kind of testing on FreeBSD, because AFAIK GitHub doesn't have any FreeBSD machines.

As long as you can get the full test suite to pass running headed as a developer, *including* the ignored tests (`cargo test -- --include-ignored`), I'm happy to have this code in the release.

**Comment by brotskydotcom** [comment] 2023-02-19 02:20
Hey @ryanavella don't worry about the PR.  I'm merging your patch.

**Closed** 2023-02-19 02:57 UTC
Labels: enhancement, help wanted
