### ISSUE TITLE
Error code 1783 on Windows

### ISSUE THREAD

**Issue by auderer** [hwchen/keyring-rs#85] opened 2022-05-26 15:44 UTC
When trying to add a keyring entry on Windows, I get `Error code 1783` which seems to correlate to `RPC_X_BAD_STUB_DATA` in winapi.

**Comment by brotskydotcom** [comment] 2022-08-07 06:35
@auderer Can you provide a minimal test program that reproduces this issue?  I can't reproduce it with `cli` example.

**Comment by brotskydotcom** [comment] 2022-09-06 16:30
@auderer Since I haven't heard from you I'm going to close this issue.  I will reopen it if you can provide a repro.

**Comment by Alexei-Barnes** [comment] 2023-01-16 16:03
I've reproduced this by providing a password that was 1,461 characters long. The reason you get this is that the validation checks if the password is over the max size (512*5 bytes) by checking the length of the string in UTF-16, in characters. Later when we store the data, we then pay the 2:1 ratio of bytes:characters, which means we exceed the allowed storage length and 💥

**Comment by brotskydotcom** [comment] 2023-01-16 16:07
Thanks very much, @Alexei-Barnes, for reproducing this, and even more for tracking down the logic error!  I'll get this fixed in both v2 and the upcoming v3.  Or feel free to submit a PR if you're so inclined.

**Comment by Alexei-Barnes** [comment] 2023-01-16 16:15
Hurmm, though, actually, I'm unconvinced by my explanation now that I've provided it.
From `&str` docs;

```
pub const fn [len](https://doc.rust-lang.org/std/primitive.str.html#method.len)(&self) -> [usize](https://doc.rust-lang.org/std/primitive.usize.html)
Returns the length of self.

This length is in bytes, not [char](https://doc.rust-lang.org/std/primitive.char.html)s or graphemes. In other words, it might not be what a human considers the length of the string.
```

**Comment by Alexei-Barnes** [comment] 2023-01-16 16:16
I'll investigate a bit and create a PR.

**Comment by brotskydotcom** [comment] 2023-01-16 16:18
I appreciate your looking at this!

**Comment by Alexei-Barnes** [comment] 2023-01-16 16:55
PR open.

**Closed** 2023-01-17 16:08 UTC
Labels: bug
